version: "3"

services:
  db:
    image: postgres:15
    platform: linux/x86_64
    container_name: todo-webapp-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - todo-webapp:/var/lib/postgresql/data
    ports:
      - ${HOST_PORT_DB}:5432
    restart: always

volumes:
  todo-webapp: